### ISSUE TITLE
QQ音乐 MP3无法转换成silk

### ISSUE THREAD

**Issue by iota9star** [mzdluo123/silk4j#4]
#### 复现步骤：
下载为MP3文件，调用转换方法
#### 测试音源：
- 地址1：[罗敷](http://isure.stream.qqmusic.qq.com/M500001kd6z43m6YjA.mp3?guid=7448997936&vkey=A5D9E92B1BB36D8CFB626FCCA75634B10A20669BEF24C16B5D172864487D58594D5307DB70904ECCC97138111DD691E346088588FFF2D2F8&uin=&fromtag=66)
- 地址2：[不问天](http://isure.stream.qqmusic.qq.com/M500001TdxNo3kIOh5.mp3?guid=7448997936&vkey=7F561A5D4ECBC1DEB60D22CC7587D4F09D971C5773830716397AB071652AAF345D67EF034247D62957C90724DCBABF16E1AE3FC898C865E2&uin=&fromtag=66)

**Comment by iota9star** [comment]
使用其他工具解决，silk4j做备用方案

**Comment by mzdluo123** [comment]
无法下载文件

**Comment by iota9star** [comment]
应该是过期了，这个播放地址应该是有时效的
