### ISSUE TITLE
非java环境使用这个项目要如何操作呢

### ISSUE THREAD

**Issue by djkcyl** [mzdluo123/silk4j#9]
我用的不是mirai的原生java插件，是http api，不管用啥方法都被压缩的离谱，想请教下有没有其他办法可以直接转码出能直接上传的高质量音频文件

**Comment by mzdluo123** [comment]
可以使用c版本的silk编码器，就在GitHub，搜索就能找到

**Comment by synodriver** [comment]
使用[rsilk](https://pypi.org/project/rsilk/)，是一个python库，当然底层还是这坨C
